import React, { useState, useEffect } from 'react';
import api from '../utils/api';
import { 
  TrendingUp, 
  Leaf, 
  ShieldAlert, 
  HelpCircle,
  Loader2,
  ChevronRight,
  Sparkles
} from 'lucide-react';

export default function Recommendations() {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const fetchRecommendations = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await api.get('/recommendations');
      setRecommendations(response.data);
    } catch (err) {
      console.error('Error fetching recommendations:', err);
      setError('Could not compile recommendations. Check API server.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, []);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-20 space-y-3">
        <Loader2 className="w-8 h-8 text-brand-500 animate-spin" />
        <p className="text-slate-400 text-sm">Running optimization scan...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 bg-red-500/10 border border-red-500/20 text-red-500 text-sm rounded-2xl">
        {error}
      </div>
    );
  }

  // Calculate cumulative potential carbon savings
  const totalSavingsCarbon = recommendations.reduce((acc, rec) => acc + rec.potentialSavingsCarbon, 0);

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            Optimization Engine
          </h1>
          <p className="text-slate-500 dark:text-slate-400 mt-1">
            Actionable optimization recommendations generated by analysis of resource usage trends.
          </p>
        </div>
      </div>

      {recommendations.length === 0 ? (
        <div className="text-center p-12 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800/80 rounded-3xl space-y-4 shadow-sm">
          <div className="w-12 h-12 bg-brand-500/10 border border-brand-500/20 rounded-full flex items-center justify-center text-brand-500 mx-auto">
            <Sparkles className="w-6 h-6" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-850 dark:text-white">All Resources Optimized</h3>
            <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">
              No optimizations detected! Your cloud workload profiles align perfectly with clean scheduling and scaling best practices.
            </p>
          </div>
        </div>
      ) : (
        <>
          {/* Carbon Savings Spotlight Card */}
          <div className="p-6 bg-gradient-to-br from-brand-900 via-brand-950 to-emerald-950 text-white rounded-3xl shadow-xl flex flex-col md:flex-row md:items-center md:justify-between gap-6 border border-emerald-900/50">
            <div className="space-y-2">
              <span className="text-xs font-bold text-brand-400 uppercase tracking-widest block">
                Total Potential Footprint Savings
              </span>
              <h2 className="text-4xl font-black flex items-baseline">
                {(totalSavingsCarbon / 1000).toFixed(3)}{' '}
                <span className="text-lg font-bold text-brand-350 ml-1">kg CO₂e</span>
              </h2>
              <p className="text-xs text-brand-200 leading-normal max-w-lg">
                By downsizing underutilized cores, deploying stop schedules, and archiving heavy storage volumes, you could significantly offset your cloud resource footprint.
              </p>
            </div>
            <div className="w-16 h-16 bg-brand-500/20 border border-brand-500/30 text-brand-400 rounded-2xl flex items-center justify-center self-start md:self-auto shrink-0">
              <Leaf className="w-8 h-8" />
            </div>
          </div>

          {/* Recommendations List */}
          <div className="space-y-4">
            <h3 className="text-lg font-bold text-slate-850 dark:text-white flex items-center">
              <TrendingUp className="w-5 h-5 text-brand-550 mr-2" /> Pending Cost & Carbon Optimizations ({recommendations.length})
            </h3>

            <div className="grid grid-cols-1 gap-4">
              {recommendations.map((rec) => (
                <div 
                  key={rec.id}
                  className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800/80 rounded-3xl p-6 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6 hover:border-slate-300 dark:hover:border-slate-700 transition-colors"
                >
                  <div className="space-y-3 flex-1">
                    {/* Tags */}
                    <div className="flex flex-wrap items-center gap-2">
                      <span className={`text-[10px] font-extrabold uppercase px-2.5 py-1 rounded-full border ${
                        rec.severity === 'High' 
                          ? 'bg-red-500/10 border-red-500/20 text-red-500' 
                          : rec.severity === 'Medium' 
                          ? 'bg-amber-500/10 border-amber-500/20 text-amber-500' 
                          : 'bg-blue-500/10 border-blue-500/20 text-blue-500'
                      }`}>
                        {rec.severity} Severity
                      </span>
                      <span className="text-[10px] font-bold uppercase px-2.5 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-650 dark:text-slate-300 border border-slate-200/50 dark:border-slate-700">
                        {rec.category}
                      </span>
                      <span className="text-xs text-slate-400">
                        Resource: <span className="font-semibold text-slate-700 dark:text-slate-200">{rec.resourceName}</span> ({rec.provider})
                      </span>
                    </div>

                    {/* Recommendation Title / Trigger */}
                    <div>
                      <h4 className="text-base font-bold text-slate-900 dark:text-white">
                        {rec.description}
                      </h4>
                      <p className="text-xs text-slate-400 mt-0.5">
                        Triggered by metric: <span className="font-semibold text-slate-600 dark:text-slate-350">{rec.triggerValue}</span>
                      </p>
                    </div>

                    {/* Description Action */}
                    <div className="bg-slate-50 dark:bg-slate-950/60 border border-slate-200/40 dark:border-slate-800/80 rounded-2xl p-3 flex items-start space-x-2 text-xs">
                      <ChevronRight className="w-4 h-4 text-brand-500 mt-0.5 shrink-0" />
                      <p className="text-slate-600 dark:text-slate-350 leading-relaxed font-medium">
                        <span className="font-bold text-slate-800 dark:text-slate-250">Recommended Action:</span> {rec.action}
                      </p>
                    </div>
                  </div>

                  {/* Savings Badge */}
                  <div className="flex md:flex-col items-center md:items-end justify-between md:justify-center border-t md:border-t-0 md:border-l border-slate-200 dark:border-slate-800 pt-4 md:pt-0 md:pl-6 shrink-0 gap-2">
                    <span className="text-xs font-semibold text-slate-400 dark:text-slate-500 uppercase tracking-wider block">
                      Potential Carbon Savings
                    </span>
                    <span className="text-xl font-extrabold text-brand-600 dark:text-brand-400 block">
                      -{rec.potentialSavingsCarbon} <span className="text-xs font-semibold text-slate-400">gCO₂e</span>
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
